### ISSUE TITLE
Manifest+ fields can be removed from module manifest, and probably should, because they cause warnings

### ISSUE THREAD

**Issue by shemetz** [reonZ/settings-markers#1]
In the Foundry setup screen, the following warning appears:

> The "Settings Markers" module's manifest contained the following unknown keys: "author", "manifestPlusVersion"

- The `author` field is no longer useful, now that we have an `authors` field
- The `manifestPlusVersion` field isn't really useful anymore, especially since Manifest+ is kind of abandoned.  In the future, if it is revived, it will use the `flags: {}` part of the manifest rather than expecting new fields.  (I asked about this in other places)

**Comment by shemetz** [comment]
Oh, and the discord username should probably be updated to `idleatre` becuase discord usernames changed last year

**Comment by reonZ** [comment]
Damn, i made those changes long time ago but never pushed them.
